/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/37gOwgzyn9D
 */
import Link from "next/link";

export function LandingPage() {
	return (
		<section className="relative w-full overflow-hidden dark:bg-gray-900">
			<img
				alt="Hero"
				className="absolute inset-0 object-cover w-full h-[100%] translate-x-1/2 scale-[1.5] sm:scale-none"
				src="/placeholder.svg"
			/>
			<div className="absolute inset-0 bg-gray-900/60 dark:bg-gray-900/80" />
			<div className="flex flex-col items-center justify-center gap-4 min-h-[600px] py-10 text-center space-y-4 md:py-16 lg:space-y-6">
				<div className="space-y-2">
					<h1 className="text-3xl font-bold tracking-tighter text-gray-100 lg:text-5xl/none dark:text-gray-900">
						Welcome to the Himalayan Homestay
					</h1>
					<p className="max-w-[700px] text-gray-300 md:text-xl dark:text-gray-400">
						Experience the serene beauty of the Himalayas in our cozy homestay
						nestled in the mountains.
					</p>
				</div>
				<div>
					<Link
						className="inline-flex items-center justify-center px-8 text-sm font-medium transition-colors bg-gray-900 rounded-md shadow h-11 text-gray-50 hover:bg-gray-900/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 dark:bg-gray-50 dark:text-gray-900 dark:hover:bg-gray-50/90 dark:focus-visible:ring-gray-300"
						href="#"
					>
						Explore More
					</Link>
				</div>
			</div>
		</section>
	);
}
